### ISSUE TITLE
Does not work in Node

### ISSUE THREAD

**Issue by matthewp** [canjs/can-dom-data-state#13]
This module can't be required from node because the main is pointed at `dist/cjs/can-dom-data-state.js` which is not published currently.

**Comment by matthewp** [comment]
I'm going to start by seeing if the publish scripts are working.

**Comment by matthewp** [comment]
This module does not have a build script. It seems to be straightforward commonjs without any steal bits, so I think it is safe to make `can-dom-data-state.js` the main. I will do that.

**Comment by justinbmeyer** [comment]
most everything in canjs should be a straighforward commonjs module.

**Comment by matthewp** [comment]
Fixed by e49d617c8afa6a16ecf6d88ce6f35210a93a7b28, released in 1.0.1
